---
dependency:
  name: galaxy
  enabled: False
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
lint: |
  set -e
  yamllint .
  # ansible-lint
  # flake8
driver:
  name: podman

platforms:
  # - name: "bootstrap-${image:-fedora}-${tag:-latest}${TOX_ENVNAME}"
  #   image: "${namespace:-robertdebock}/${image:-fedora}:${tag:-latest}"
  #   command: /sbin/init
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   privileged: True
  #   pre_build_image: True

  - name: tuned-almalinux8
    image: quay.io/maodevops/almalinux8-systemd:latest
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: True
    pre_build_image: True
    # capabilities:
    #   - SYS_ADMIN
  - name: tuned-almalinux9
    image: quay.io/maodevops/almalinux9-systemd:latest
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: True
    pre_build_image: True
  - name: tuned-amazonlinux2
    image: quay.io/maodevops/amazonlinux2-systemd:latest
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: True
    pre_build_image: True
  - name: tuned-centos7
    image: quay.io/maodevops/centos7-systemd:latest
    command: /sbin/init
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    capabilities:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    privileged: True
    pre_build_image: True
  - name: tuned-debian11
    image: quay.io/maodevops/debian11-systemd:latest
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: True
    pre_build_image: True
  - name: tuned-fedora36
    image: quay.io/maodevops/fedora36-systemd:latest
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: True
    pre_build_image: True
  - name: tuned-opensuse-leap15.3
    image: quay.io/maodevops/opensuse-leap15.3-systemd:latest
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: True
    pre_build_image: True
  - name: tuned-opensuse-leap15.4
    image: quay.io/maodevops/opensuse-leap15.4-systemd:latest
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: True
    pre_build_image: True
  - name: tuned-rockylinux8
    image: quay.io/maodevops/rockylinux8-systemd:latest
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: True
    pre_build_image: True
  - name: tuned-rockylinux9
    image: quay.io/maodevops/rockylinux9-systemd:latest
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: True
    pre_build_image: True
  # - name: tuned-ubuntu2204
  #   image: quay.io/maodevops/ubuntu22.04-systemd:latest
  #   command: /lib/systemd/systemd
  #   tmpfs:
  #     - /run/lock
  #     - /run
  #     - /tmp
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   privileged: True
  #   pre_build_image: True
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  create_sequence:
    - create
  check_sequence:
    - create
    - converge
    - check
    - destroy
  converge_sequence:
    - create
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    # - lint
    # - destroy
    # - syntax
    - create
    - converge
    #- idempotence
    #- verify
    - destroy
