---
# handlers file for daos

- name: restart daos_server service
  ansible.builtin.service:
    name: daos_server
    state: restarted
  tags: all

- name: restart daos_agent service
  ansible.builtin.service:
    name: daos_agent
    state: restarted
  tags: all
