---

- name: Include server configuration tasks
  ansible.builtin.include_tasks: config_server.yml
  args:
    apply:
      tags:
        - daos
        - daos_config
  tags:
    - daos
    - daos_config
  when: '"server" in daos_roles'

- name: Create daos_control.yml file
  ansible.builtin.template:
    src: 'etc/daos/daos_control_{{ daos_config_version }}.yml.j2'
    dest: '/etc/daos/daos_control.yml'
    owner: root
    group: root
    mode: '0644'
  tags:
    - daos
    - daos_config
