---

# If iommu is not enabled we have to run the daos_server service as root
- name: Determine daos_server_user based on intel_iommu=on
  ansible.builtin.shell: |
    if grep -i -q 'intel_iommu=on' /proc/cmdline; then
      echo {{ daos_server_user | default('daos_server') }}
    else
      echo root
    fi
  register: daos_config_server_user
  changed_when: false

- name: Include server configuration tasks
  ansible.builtin.include_tasks: config_server.yml
  args:
    apply:
      tags:
        - daos
        - daos_config
  tags:
    - daos
    - daos_config
  when: '"server" in daos_roles'
