---

- name: config | Create daos_control.yml file
  ansible.builtin.template:
    src: 'etc/daos/{{ daos_config_version }}/daos_control.yml.j2'
    dest: '/etc/daos/daos_control.yml'
    owner: root
    group: root
    mode: '0644'
    backup: true
  tags:
    - daos
    - daos_config

- name: config | Include server configuration tasks
  ansible.builtin.import_tasks: config_server.yml
  when: daos_role_server in daos_roles
  tags:
    - daos
    - daos_config

- name: config | Include client configuration tasks
  ansible.builtin.import_tasks: config_client.yml
  when: daos_role_client in daos_roles
  tags:
    - daos
    - daos_config

- name: config | Include admin configuration tasks
  ansible.builtin.import_tasks: config_admin.yml
  when: daos_role_admin in daos_roles
  tags:
    - daos
    - daos_config
