---
# RedHat installation tasks for daos

- name: Import epel-release GPG key
  ansible.builtin.rpm_key:
    key: 'https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}'
    state: present
  when: ansible_distribution|lower == "rhel"

- name: Install epel-release from RPMs
  ansible.builtin.dnf:
    name: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm'
    state: present
  when: ansible_distribution|lower == "rhel"

- name: Create repo file
  ansible.builtin.template:
    src: 'repofiles/daos.repo.{{ ansible_pkg_mgr }}.j2'
    dest: '{{ daos_repo_files_dir }}/daos.repo'
    owner: root
    group: root
    mode: '0644'

- name: Install dependent packages
  ansible.builtin.package:
    name: '{{ daos_dep_pkgs }}'
    state: present

- name: Install DAOS packages
  ansible.builtin.package:
    name: '{{ daos_pkgs[item] | default([]) }}'
    state: present
  loop: '{{ daos_roles }}'

- name: Create daos server log directory
  ansible.builtin.file:
    path: "{{ daos_server_log_dir }}"
    state: directory
    owner: "{{ daos_server_user }}"
    group: "{{ daos_server_user }}"
  when: '"server" in daos_roles'

- name: Enable daos_server service
  ansible.builtin.service:
    name: daos_server
    enabled: yes
  when: '"server" in daos_roles'
