---
# main tasks file for daos

- name: Import assert.yml
  ansible.builtin.import_tasks: assert.yml
  tags:
    - daos
    - daos_assert
    - daos_install
    - daos_certs
    - daos_config
    - daos_admin

- name: Include distro family specific install.yml
  ansible.builtin.include_tasks: '{{ daos_install_task_file }}'
  tags:
    - daos
    - daos_install

# - name: Include certificate deployment tasks
#   ansible.builtin.include_tasks: certs.yml
#   args:
#     apply:
#       tags:
#         - daos
#         - daos_certs
#   tags:
#     - daos
#     - daos_certs
#   when: daos_deploy_certs

- name: Include config tasks
  ansible.builtin.include_tasks: config.yml
  tags:
    - daos
    - daos_config

- name: Include admin tasks
  ansible.builtin.include_tasks: admin.yml
  tags:
    - daos
    - daos_admin
