---
# main tasks file for daos

- name: Import assert.yml
  ansible.builtin.import_tasks: assert.yml
  tags:
    - daos
    - daos_assert
    - daos_install

- name: Include distro family specific install.yml
  ansible.builtin.include_tasks: '{{ daos_install_task_file }}'
  args:
    apply:
      tags:
        - daos
        - daos_install

# - name: Include configure tasks
#   ansible.builtin.include_tasks: configure.yml
#   args:
#     apply:
#       tags:
#         - daos
#         - daos_configure
