---
# IOMMU configuration tasks for the tune role

- name: Register IOMMU support
  ansible.builtin.shell: |
    if dmesg | grep -q -i 'DMAR: IOMMU\|DMAR-IR.*IOMMU\|iommu group'; then
      echo "true"
    else
      echo "false"
    fi
  changed_when: false
  register: tune_iommu_support

- name: Register IOMMU grub enabled
  ansible.builtin.shell: |
    if grep -q -i 'intel_iommu=on' /etc/default/grub; then
      echo "true"
    else
      echo "false"
    fi
  changed_when: false
  register: tune_iommu_grub_enabled

- name: 'Insert intel_iommu=on in /etc/default/grub if missing'
  ansible.builtin.lineinfile:
    backrefs: true
    path: /etc/default/grub
    regexp: '^(GRUB_CMDLINE_LINUX_DEFAULT=".*)"$'
    line: '\1 intel_iommu=on"'
  when: tune_iommu_support.stdout | default(false) | bool
    and not (tune_iommu_grub_enabled.stdout | bool)
  register: tune_iommu_grub

- name: Run grub2-mkconfig
  ansible.builtin.shell: grub2-mkconfig --output=/boot/grub2/grub.cfg
  when: tune_iommu_grub.changed
  register: tune_grub

- name: Show reboot required message
  ansible.builtin.debug:
    msg: "/etc/default/grub has changed. A reboot is required!"
  when: tune_grub.changed
