---
# network tuning tasks for the tune role

# TODO: Need to figure out how to set MTU on openSUSE Leap 15.
#       This task will fail because nmcli is not present. Maybe use yast?
- name: "Set MTU on {{ ansible_default_ipv4.interface }}"
  community.general.nmcli:
    conn_name: "System eth0" # "{{ ansible_default_ipv4.interface }}"
    mtu: "{{ tune_nic_default_ipv4_mtu | default('1500') }}"
    type: ethernet
    state: present
  when: ansible_os_family | lower != "suse"

- name: Auto configure combined NIC queues
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      nr_cpus=$(lscpu -p | grep -v '^#' | sort -t, -k 2,4 -u | wc -l)
      hw_queues=$(/usr/sbin/ethtool -l {{ ansible_default_ipv4.interface }} | \
                  grep -A4 maximums | tail -n 1 | cut -d':' -f2)
      queues=$(( nr_cpus > hw_queues ? hw_queues : nr_cpus))
      /usr/sbin/ethtool -L {{ ansible_default_ipv4.interface }} combined $queues
    warn: false
  register: tune_nic_queues_auto
  failed_when: tune_nic_queues_auto.rc != 0 and tune_nic_queues_auto.stderr is not search("unmodified")
  changed_when: tune_nic_queues_auto.stderr is not search("unmodified")
  when: tune_nic_queues_auto_enabled | default(false) | bool

- name: Register current combined NIC queues
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      /usr/sbin/ethtool -l "{{ ansible_default_ipv4.interface }}" | \
      grep -A4 Current | grep Combined | awk '{print $2}'
  register: tune_nic_queues_current
  changed_when: false

- name: Set combined NIC queues
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      /usr/sbin/ethtool -L "{{ ansible_default_ipv4.interface }}" \
      combined "{{ tune_nic_queues_combined }}"
    warn: false
  register: tune_nic_queues
  failed_when: tune_nic_queues.rc != 0 and tune_nic_queues.stderr is not search("unmodified")
  changed_when: tune_nic_queues_current.stdout | int != tune_nic_queues_combined | int
  when: not (tune_nic_queues_auto_enabled | default(false) | bool)
