---
# tune tasks file for daos


# readonly TUNED_PROFILE="network-latency"
# readonly SYSCTL_CONF="/etc/sysctl.conf"
# readonly NIC="eth0"
# readonly SELINUX_CONFIG="/etc/selinux/config"

# update_sysctl()
# {
#   local key=$1
#   shift
#   local value=$*
#   echo "Updating sysctl key=$key, value=$value"
#   touch $SYSCTL_CONF
#   local regex="s/^\s*${key}\s*=.*$/${key} = ${value}/g"
#   sed -i "$regex" "$SYSCTL_CONF"
#   if ! grep -Fq "$key" "$SYSCTL_CONF"; then
#     echo "sysctl $key not found, appending to $SYSCTL_CONF"
#     echo "$key = $value" >> "$SYSCTL_CONF"
#   fi
# }

# echo "Use $TUNED_PROFILE profile in tuned-adm"
# tuned-adm profile $TUNED_PROFILE

# echo "Tune TCP Memory"
# update_sysctl net.ipv4.tcp_rmem 4096 87380 16777216
# update_sysctl net.ipv4.tcp_wmem 4096 16384 16777216
# sysctl -p

ethtool -i eth0 | grep driver | cut -d':' -f2 | xargs

# echo "Tune NIC queues"
# driver=$(ethtool -i $NIC | grep driver | cut -d':' -f2 | xargs)
# if [[ "$driver" == "virtio_net" ]]; then
#   nr_cpus=$(lscpu -p | grep -v '^#' | sort -t, -k 2,4 -u | wc -l)
#   hw_queues=$(ethtool -l ${NIC} | grep -A4 maximums | tail -n 1 | cut -d':' -f2)
#   queues=$(( nr_cpus > hw_queues ? hw_queues : nr_cpus))
#   ethtool -L $NIC combined $queues
# fi

# echo "Disable SELinux"
# sed -i 's/^SELINUX=.*$/SELINUX=disabled/g' $SELINUX_CONFIG

# echo "Disable firewalld"
# systemctl stop firewalld
# systemctl disable firewalld

set_fact:
  nic: "{{ ansible_default_ipv4.interface }}"
  nic_mtu: "{{ ansible_default_ipv4.interface.mtu }}"
  nic_driver: "{{ ansible_facts["ansible"~ansible_default_ipv4.interface].module }}"
  cpus: "{{ ansible_processor_count }}"



        "ansible_default_ipv4": {
            "address": "10.11.13.5",
            "alias": "eth0",
            "broadcast": "10.11.255.255",
            "gateway": "10.11.255.1",
            "interface": "eth0",
             "mtu": 1500,
        "ansible_processor_cores": 1,
        "ansible_processor_count": 2,
        "ansible_processor_nproc": 2,
        "ansible_processor_threads_per_core": 1,
        "ansible_processor_vcpus": 2,
ansible_processor_count = 2

$ cat /etc/sysctl.conf
# sysctl settings are defined through files in
# /usr/lib/sysctl.d/, /run/sysctl.d/, and /etc/sysctl.d/.
#
# Vendors settings live in /usr/lib/sysctl.d/.
# To override a whole file, create a new file with the same in
# /etc/sysctl.d/ and put new settings there. To override
# only specific settings, add a file with a lexically later
# name in /etc/sysctl.d/ and put new settings there.
#
# For more information, see sysctl.conf(5) and sysctl.d(5).

# Per CCE-80916-0: Set kernel.randomize_va_space = 2 in /etc/sysctl.conf

kernel.randomize_va_space=2
net.ipv4.tcp_max_syn_backlog=65536
net.ipv4.tcp_timestamps=0
net.ipv4.tcp_sack=1
net.core.netdev_max_backlog=250000
net.core.rmem_max=16777216
net.core.wmem_max=16777216
net.core.rmem_default=16777216
net.core.wmem_default=16777216
net.core.optmem_max=16777216
net.ipv4.tcp_rmem=4096 87380 16777216
net.ipv4.tcp_wmem=4096 65536 16777216
net.ipv4.tcp_low_latency=1
net.ipv4.tcp_adv_win_scale=1
net.core.somaxconn=2048
net.ipv4.neigh.ens1.gc_stale_time=2000000
net.ipv4.neigh.ens1.base_reachable_time_ms=120000
net.ipv4.neigh.ens1.mcast_solicit=18
