---
# playbook: daos_local.yml
# description: Installs DAOS on localhost.
#              This playbook was intended to be run by a startup/user_data script.
# run: ansible-playbook daos_local.yml --extra-vars="daos_roles=['admin','server','client']"

- name: Install DAOS
  hosts: "{{ target | default('localhost') }}"
  gather_facts: yes

  collections:
    - mark_olson.daos

  roles:
    - role: tune
      tags:
        - tune
        - tune_tuned
        - tune_network
    - role: daos
      tags:
        - daos
        - daos_install
        - daos_configure
