---
# playbook:     daos_cluster.yml
# playbook_fqn: daos_stack.daos.daos_cluster

- name: DAOS cluster prep
  hosts: all
  gather_facts: yes
  become: yes

  roles:
    - role: daos_stack.daos.epel
    - role: daos_stack.daos.packages
    - role: daos_stack.daos.tune
    - role: daos_stack.daos.reboot

- name: DAOS cluster installation and configuration
  hosts: all
  gather_facts: yes
  become: yes

  pre_tasks:
    - name: Create access_points group
      add_host:
        name: "{{ item }}"
        groups: access_points
      when: hostvars[item].is_access_point | default(false) | bool
      with_items: "{{  groups['daos_servers'] }}"
      changed_when: false

    - name: Create daos_access_points IP list
      set_fact:
        daos_access_points: "{{ groups.access_points | map('extract', hostvars, 'ansible_default_ipv4') | map(attribute='address') | list }}"

  roles:
    - role: daos_stack.daos.daos
